name: Business Communications APIs
subtitle: Developer Center
base_url: 'https://developer.uc.vonage.com'
assets:
  header_logo:
    path: '/images/logos/vbc-logo.svg'
    alt: 'VBC Logo'
  footer_logo:
    path: '/images/logos/vbc-logo-white.svg'
    alt: 'VBC Footer Logo'
docs_repo: 'VonageGarage/VDP'
oas_url: 'https://www.github.com/VonageGarage/VDP/blob/master/_open_api/definitions'
header:
  links:
    sign-up:
      path: https://apimanager.uc.vonage.com
      text:
        - try-it
        - get_an_api_key
        - start_building
  hiring:
    display: false
footer:
  links:
    navigation:
      documentation:
        - call-recording: '/call-recording/overview'
        - provisioning: '/provisioning/overview'
        - telephony: '/telephony/overview'
        - reports: '/reports/overview'
        - vonage-integration-platform: '/vonage-integration-platform/overview'
        - smart-numbers: '/smart-numbers/overview'
      api-reference:
        - call-recording: '/api/call-recording'
        - provisioning: '/api/provisioning'
        - telephony: '/api/telephony'
        - reports: '/api/reports'
        - vonage-integration-platform: '/api/vonage-integration-platform'
      get-to-know-us:
        - vonage-business-communications: 'https://www.vonage.com/unified-communications/'
        - careers: 'https://www.vonage.com/corporate/careers/'
        - press: 'https://www.vonage.com/corporate'
    support:
      business-support: 'https://businesssupport.vonage.com/'
      developer-support: 'https://businesssupport.vonage.com/contactus'
    social:
      linkedin: 'https://www.linkedin.com/company/vonage/'
      twitter: 'https://twitter.com/vonage'
