products:
  - 
    name: 'Call Recording'
    icon: 'phone'
    icon_colour: 'blue'
    path: 'call-recording'
    dropdown: true
  - 
    name: 'Node RED'
    icon: 'flow'
    icon_colour: 'red'
    path: 'node-red'
    dropdown: true
  - 
    name: 'Provisioning'
    icon: 'phone'
    icon_colour: 'green'
    path: 'provisioning'
    dropdown: true
  - 
    name: 'Reports'
    icon: 'file-search'
    icon_colour: 'purple-dark'
    path: 'reports'
    dropdown: true
  - 
    name: 'Smart Numbers'
    icon: 'queue'
    icon_colour: 'yellow'
    path: 'smart-numbers'
    dropdown: true
  - 
    name: 'Telephony'
    icon: 'phone'
    icon_colour: 'black'
    path: 'telephony'
    dropdown: true
  - 
    name: 'Vonage Integration Platform'
    icon: 'chat'
    icon_colour: 'blue'
    path: 'vonage-integration-platform'
    dropdown: true
  - 
    name: 'Zapier'
    icon: 'lock'
    icon_colour: 'blue'
    path: 'zapier'
    dropdown: true
  - 
    name: 'Getting Started'
    icon: 'mind-map'
    icon_colour: 'green'
    path: 'getting-started'
    dropdown: false
  -
    name: 'Call Logs'
    icon: 'icon-history'
    icon_colour: 'green'
    path: 'call-logs'
    dropdown: true
